namespace: community
name: azuredevops
version: 1.0.0
readme: README.md
authors:
  - Eduardo Lucas <elucas@sequentia.nl>
description: Ansible modules for automating Azure DevOps
license:
  - GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/edvlucas/azuredevops-ansible-collection
documentation: https://github.com/edvlucas/azuredevops-ansible-collection
homepage: https://github.com/edvlucas/azuredevops-ansible-collection
issues: https://github.com/edvlucas/azuredevops-ansible-collection/issues
build_ignore: []
